---
spring:
  application:
    name: article-service
  datasource:
    url: jdbc:postgresql://localhost:5430/localDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver

service:
  messages.article-created: Article successfully created

